<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
<div class="menu_section">
<br><br><br>
<ul class="nav side-menu">
	<li><a><i class="fa fa-home"></i>Home<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('index') ?>">Dashboard</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-users"></i>Human Resource<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>HR Administration<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Leave<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('leavestatus') ?>">Apply Leave</a></li>
						<li><a href="<?php echo $this->url('empleaveapproval') ?>">Leave Approval</a></li>
						<li><a href="<?php echo $this->url('staffleavestatus') ?>">My Leave Status</a></li>
						<li><a href="<?php echo $this->url('applyonbehalfleave') ?>">Apply Leave On Behalf</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Leave Encashment<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empleaveencashmentapplication') ?>">Leave Encashment</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Staff Task<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('employeetaskcategory') ?>">Add Task/Project</a></li>
						<li><a href="<?php echo $this->url('addempemployeetaskrecord') ?>">Add Self Activities</a></li>
						<li><a href="<?php echo $this->url('employeetaskrecord') ?>">Add Other Staff Activities</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Department Filing<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('viewfilingdocument') ?>">View Documents</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Lifecycle<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Transfer<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('applytransferform') ?>">Apply Transfer</a></li>
						<li><a href="<?php echo $this->url('stafftransferstatus') ?>">My Transfer Status</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Promotion<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empapplypromotion') ?>">Apply Promotion</a></li>
						<li><a href="<?php echo $this->url('staffpromotionstatus') ?>">My Promotion Status</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Separation<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('empresignation') ?>">Apply Resignation</a></li>
						<li><a href="<?php echo $this->url('staffresignationstatus') ?>">My Resignation Status</a></li>
						<li><a href="<?php echo $this->url('separationrecordlist') ?>">Separation Record List</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>PMS<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Appraisals<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('administrativeappraisal') ?>">Administrative Appraisal</a></li>
					</ul>
					</li>
			</ul>
			</li>
			<li><a><i class=""></i>Recruitment<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('employeeonprobation') ?>">Regularize Staff</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Tour<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('emptravelauthorization') ?>">Travel Authorization</a></li>
					<li><a href="<?php echo $this->url('emptravellist') ?>">Travel Approval</a></li>
					<li><a href="<?php echo $this->url('stafftourstatus') ?>">Travel Status</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Staff Management<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('employeelist') ?>">Staff List</a></li>
					<li><a href="<?php echo $this->url('empprofilepicture') ?>">Staff Profile Picture</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-bank"></i>Admission<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Student Section<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('edit-student-section') ?>">Update Student Section</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student House<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('add-new-house') ?>">Add New House</a></li>
					<li><a href="<?php echo $this->url('add-new-student-house') ?>">Add New Student House</a></li>
					<li><a href="<?php echo $this->url('edit-student-house') ?>">Edit Student House</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Student Details<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('studentlists') ?>">Student Lists</a></li>
					<li><a href="<?php echo $this->url('studentpersonaldetails') ?>">Student Personal Details</a></li>
					<li><a href="<?php echo $this->url('studentpermanentaddressdetails') ?>">Student Permanent Address</a></li>
					<li><a href="<?php echo $this->url('studentrelationdetails') ?>">Student Relation Details</a></li>
					<li><a href="<?php echo $this->url('studentpreviousschooldetails') ?>">Student Previous School Details</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Parent Portal Access<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('parentportalaccess') ?>">Assign Parent</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Admission Report<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('yearwisestudentreports') ?>">Year Wise Report</a></li>
					<li><a href="<?php echo $this->url('overallstudentreports') ?>">Overall Report</a></li>
			</ul>
			</li>
			<li><a href="<?php echo $this->url('add-student-type') ?>">Student Type</a></li>
			<li><a href="<?php echo $this->url('add-student-category') ?>">Student Category</a></li>
			<li><a href="<?php echo $this->url('registered-student-list') ?>">Student Admission</a></li>
			<li><a href="<?php echo $this->url('new-registered-student-list') ?>">Report New Student</a></li>
			<li><a href="<?php echo $this->url('new-reported-student-list') ?>">Generate Student ID</a></li>
			<li><a href="<?php echo $this->url('reported-student-list') ?>">Update Reported Student List</a></li>
			<li><a href="<?php echo $this->url('add-new-student') ?>">Add New Student (College)</a></li>
			<li><a href="<?php echo $this->url('register-student-semester') ?>">Student Semester Registration</a></li>
			<li><a href="<?php echo $this->url('semesterreportedstudentlist') ?>">Update Student Status</a></li>
			<li><a href="<?php echo $this->url('programmechange') ?>">Student Change Programme</a></li>
		</ul>
	</li>
	<li><a><i class="fa fa-database"></i>Property and Inventory<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a><i class=""></i>Goods Transaction<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a><i class=""></i>Goods Issue<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('add-adhoc-goods-issue') ?>">Adhoc</a></li>
						<li><a href="<?php echo $this->url('requisition-goods-issue') ?>">Requisition</a></li>
						<li><a href="<?php echo $this->url('sub-store-issue-goods') ?>">Sub Store</a></li>
						<li><a href="<?php echo $this->url('add-sub-store-to-ind-issue-goods') ?>">Sub Store to Individual</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Goods Surrender<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('goods-surrender-list') ?>">Status</a></li>
						<li><a href="<?php echo $this->url('applied-goods-surrender-list') ?>">All Status</a></li>
						<li><a href="<?php echo $this->url('emp-goods-surrender-list') ?>">Store Approval</a></li>
						<li><a href="<?php echo $this->url('emp-sub-store-goods-surrender-list') ?>">Sub Store Approval</a></li>
						<li><a href="<?php echo $this->url('sub-store-surrender-list') ?>">Sub Store To Store Approval</a></li>
					</ul>
					</li>
					<li><a><i class=""></i>Goods Transfer<span class="fa fa-chevron-down"></span></a>
					<ul class="nav child_menu">
						<li><a href="<?php echo $this->url('dept-goods-transfer-from-list') ?>">From Department</a></li>
						<li><a href="<?php echo $this->url('dept-goods-transfer-list') ?>">Goods Transfer Status</a></li>
						<li><a href="<?php echo $this->url('org-goods-transfer-approval-list') ?>">From Organisation Approval List</a></li>
						<li><a href="<?php echo $this->url('org-goods-transfer-list') ?>">Organisation Goods Transfer Status</a></li>
					</ul>
					</li>
					<li><a href="<?php echo $this->url('view-item-details') ?>">Add Item Details</a></li>
					<li><a href="<?php echo $this->url('add-item-supplier') ?>">Supplier</a></li>
					<li><a href="<?php echo $this->url('add-item-donor') ?>">Donor</a></li>
					<li><a href="<?php echo $this->url('add-goods-received') ?>">Stock Entry</a></li>
					<li><a href="<?php echo $this->url('supplied-goods-list') ?>">Generate Receipt Voucher</a></li>
					<li><a href="<?php echo $this->url('view-goods-in-stock') ?>">Goods in Stock</a></li>
					<li><a href="<?php echo $this->url('emp-goods-list') ?>">My Goods List</a></li>
					<li><a href="<?php echo $this->url('view-dept-goods-list') ?>">Sub Stock Lists</a></li>
					<li><a href="<?php echo $this->url('dept-all-goods-in-stock') ?>">All Department Goods in Stock</a></li>
					<li><a href="<?php echo $this->url('view-emp-issued-goods') ?>">Staff Issued Goods List</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Goods Requisition<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('apply-goods-requisition') ?>">Apply Requisition</a></li>
					<li><a href="<?php echo $this->url('view-requisition') ?>">Requisition List</a></li>
					<li><a href="<?php echo $this->url('requisition-approval-list') ?>">Requisition Approval</a></li>
					<li><a href="<?php echo $this->url('list-all-requisition') ?>">List all requisition</a></li>
					<li><a href="<?php echo $this->url('all-goods-requisition-list') ?>">All Requisition List</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Goods Depreciation<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('view-fixed-asset-list') ?>">Fixed Assets List</a></li>
					<li><a href="<?php echo $this->url('view-depreciation-value') ?>">Depreciation Table</a></li>
			</ul>
			</li>
			<li><a><i class=""></i>Property & Inventory Reports<span class="fa fa-chevron-down"></span></a>
			<ul class="nav child_menu">
					<li><a href="<?php echo $this->url('inventoryreports') ?>">Inventory Reports</a></li>
			</ul>
			</li>
		</ul>
	</li>
	<li><a><i class="fa fa-user"></i>Counseling Service<span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="<?php echo $this->url('counselingappointment') ?>">Seek Appointment</a></li>
		</ul>
	</li>
</ul>
</div>
</div>
